# Generated by Django 4.0.2 on 2022-02-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField(default='https://www.yektanet.com/')),
                ('image_url', models.URLField(default='../img/404.jpg')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BaseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(verbose_name='action_time')),
                ('user_ip', models.GenericIPAddressField(verbose_name='user IP')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_system.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('basestat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ad_system.basestat')),
            ],
            bases=('ad_system.basestat',),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('basestat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ad_system.basestat')),
            ],
            bases=('ad_system.basestat',),
        ),
        migrations.AddField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_system.advertiser'),
        ),
    ]
