# Generated by Django 4.0.2 on 2022-02-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=100)),
                ('ad_link', models.CharField(max_length=200)),
                ('ad_image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BaseClicksAndView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(verbose_name='action_time')),
                ('user_ip', models.GenericIPAddressField(verbose_name='user IP')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_system.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('baseclicksandview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ad_system.baseclicksandview')),
            ],
            bases=('ad_system.baseclicksandview',),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('baseclicksandview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ad_system.baseclicksandview')),
            ],
            bases=('ad_system.baseclicksandview',),
        ),
        migrations.AddField(
            model_name='ad',
            name='advertiser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_system.advertiser'),
        ),
    ]
