# Generated by Django 4.0.2 on 2022-02-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(),
        ),
    ]
