# Generated by Django 4.0.2 on 2022-02-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_title',
            field=models.CharField(max_length=50),
        ),
    ]
