# Generated by Django 4.0.2 on 2022-02-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_system', '0002_alter_ad_image_url_alter_ad_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
            ],
        ),
    ]
